#!/usr/bin/env python3
"""Build the Springer media-enhancement manifest from manuscript links and registry entries."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "compliance" / "media-enhancements.yml"
TOOL_DIR = ROOT / "tools" / "registry"
URL_RE = re.compile(r'https?://[^\s)>\]}`"]+')

MANUSCRIPT_UNITS = {
    "front": ROOT / "book" / "index.qmd",
    **{
        f"ch{number:02d}": next(
            (ROOT / "book" / "chapters").glob(f"{number:02d}-*/index.qmd")
        )
        for number in range(1, 11)
    },
    "appA": ROOT / "book" / "appendices" / "appendix-a-bootstrapping" / "index.qmd",
    "appB": ROOT / "book" / "appendices" / "appendix-b-design-loop-card" / "index.qmd",
    # appendix-c-architecture-20-resources was refactored out (commit 84316bc5); its
    # tool/lab/repo links were pruned from COMPANION_METADATA below on 2026-07-19.
}

PROJECT_OWNER = "Vijay Janapa Reddi / Harvard Edge project"

COMPANION_METADATA: dict[str, dict[str, str]] = {
    "https://arch2.mlsysbook.ai/design-loop-card/template.md": {
        "purpose": "downloadable companion form",
        "owner": PROJECT_OWNER,
        "nature": "download",
        "description": "Markdown form for completing and reviewing a design-loop card.",
    },
    "https://arch2.mlsysbook.ai/design-loop-card/template.yaml": {
        "purpose": "downloadable machine-readable companion template",
        "owner": PROJECT_OWNER,
        "nature": "download",
        "description": "YAML template for a machine-checkable design-loop card.",
    },
    "https://arch2.mlsysbook.ai/examples/design-loop-cards/array-study-v2.yaml": {
        "purpose": "synthetic companion example",
        "owner": PROJECT_OWNER,
        "nature": "example",
        "description": "Synthetic schema-valid card and replay fixture used to teach the contract.",
    },
    "https://arch2.mlsysbook.ai/schemas/design-loop-card.v2.schema.json": {
        "purpose": "machine-readable companion contract",
        "owner": PROJECT_OWNER,
        "nature": "schema",
        "description": "Published JSON Schema for design-loop card version 2.0.",
    },
    "https://arch2.mlsysbook.ai/start.html": {
        "purpose": "guided companion workflow",
        "owner": PROJECT_OWNER,
        "nature": "site",
        "description": "Thirty-minute workflow for drafting and validating a bounded context-profile card.",
    },
    # Pruned 2026-07-19: six tool/lab/repo links formerly surfaced only by the
    # refactored-out appendix-c-architecture-20-resources; no longer present in the book.
}

HEADER = """# Generated by .github/scripts/build_media_enhancements.py.
# Edit the direct-link metadata in that script or the source files in tools/registry/.
# Owner identifies the credited project steward or institution for delivery routing;
# it is not a determination of copyright ownership.
# Existing external URLs last checked: 2026-07-14; release-local assets are
# validated by the publication workflow.
"""


def direct_links() -> dict[str, list[str]]:
    links: dict[str, list[str]] = {}
    for chapter, path in MANUSCRIPT_UNITS.items():
        text = path.read_text(encoding="utf-8")
        for match in URL_RE.findall(text):
            url = match.rstrip(".,;:")
            links.setdefault(url, []).append(chapter)
    return {url: sorted(set(chapters)) for url, chapters in links.items()}


def companion_entries() -> list[dict[str, Any]]:
    links = direct_links()
    unknown = sorted(set(links) - set(COMPANION_METADATA))
    stale = sorted(set(COMPANION_METADATA) - set(links))
    if unknown or stale:
        details: list[str] = []
        if unknown:
            details.append(f"missing metadata for direct links: {unknown}")
        if stale:
            details.append(f"metadata no longer used by manuscript: {stale}")
        raise ValueError("; ".join(details))

    entries: list[dict[str, Any]] = []
    for url in sorted(links):
        metadata = COMPANION_METADATA[url]
        entries.append(
            {
                "url": url,
                "purpose": metadata["purpose"],
                "chapters": links[url],
                "owner": metadata["owner"],
                "nature": metadata["nature"],
                "description": metadata["description"],
                "source": "direct manuscript link",
            }
        )
    return entries


def registry_entries() -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for path in sorted(TOOL_DIR.glob("*.yml")):
        item = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(item, dict):
            raise ValueError(f"{path}: expected a mapping")
        missing = [
            field
            for field in ("title", "url", "artifact_type", "description", "institution")
            if not item.get(field)
        ]
        if missing:
            raise ValueError(f"{path}: missing delivery fields {missing}")
        entry: dict[str, Any] = {
            "url": item["url"],
            "purpose": f"living registry entry for {item['title']}",
            # sourced from the tool registry (tools/registry/), not a manuscript unit;
            # the former appendix-c-architecture-20-resources that surfaced these was refactored out.
            "chapters": ["tool-registry"],
            "owner": item["institution"],
            "nature": str(item["artifact_type"]).lower(),
            "description": item["description"],
            "source": str(path.relative_to(ROOT)),
        }
        if item.get("authors"):
            entry["credits"] = item["authors"]
        if item.get("last_verified"):
            entry["last_verified"] = item["last_verified"]
        entries.append(entry)
    return sorted(entries, key=lambda entry: (entry["purpose"].lower(), entry["url"]))


def rendered_manifest() -> str:
    entries = companion_entries() + registry_entries()
    urls = [entry["url"] for entry in entries]
    duplicates = sorted({url for url in urls if urls.count(url) > 1})
    if duplicates:
        raise ValueError(f"duplicate manifest URLs: {duplicates}")
    body = yaml.safe_dump(
        {"media_enhancements": entries},
        sort_keys=False,
        allow_unicode=True,
        width=100,
    )
    return HEADER + body


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if the checked-in manifest is stale"
    )
    args = parser.parse_args()
    rendered = rendered_manifest()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is stale", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is current")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    count = len(yaml.safe_load(rendered)["media_enhancements"])
    print(f"Built {OUTPUT.relative_to(ROOT)} with {count} entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
