#!/usr/bin/env python3
"""Build the Quarto workshop index from one YAML file per workshop."""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

from workshop_common import WORKSHOPS_DIR, WORKSHOPS_PATH


def load_items() -> list[dict]:
    items: list[dict] = []
    for path in sorted(Path(WORKSHOPS_DIR).glob("*.yml")):
        with path.open(encoding="utf-8") as handle:
            item = yaml.safe_load(handle) or {}
        if not isinstance(item, dict):
            raise ValueError(f"{path}: expected a mapping")
        item.setdefault("source_file", path.name)
        items.append(item)
    return sorted(
        items, key=lambda item: (item.get("order", 9999), item.get("title", ""))
    )


def main() -> int:
    items = load_items()
    output = Path(WORKSHOPS_PATH)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as handle:
        handle.write(
            "# Generated by .github/scripts/build_workshops_index.py; "
            "edit www/workshops/*.yml.\n"
        )
        yaml.dump(
            items, handle, sort_keys=False, default_flow_style=False, allow_unicode=True
        )
    print(f"Built {WORKSHOPS_PATH} from {len(items)} workshop file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
