#!/usr/bin/env python3
"""Build the Quarto reading-list index from one YAML file per resource."""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

from reading_common import READINGS_DIR, READINGS_PATH


def load_items() -> list[dict]:
    items: list[dict] = []
    for path in sorted(Path(READINGS_DIR).glob("*.yml")):
        with path.open(encoding="utf-8") as handle:
            item = yaml.safe_load(handle) or {}
        if not isinstance(item, dict):
            raise ValueError(f"{path}: expected a mapping")
        item.setdefault("source_file", path.name)
        items.append(item)
    return sorted(
        items, key=lambda item: (item.get("order", 9999), item.get("title", ""))
    )


def main() -> int:
    items = load_items()
    output = Path(READINGS_PATH)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as handle:
        handle.write(
            "# Generated by .github/scripts/build_readings_index.py; "
            "edit www/readings/*.yml.\n"
        )
        yaml.dump(
            items, handle, sort_keys=False, default_flow_style=False, allow_unicode=True
        )
    print(f"Built {READINGS_PATH} from {len(items)} resource file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
