#!/usr/bin/env python3
"""Render the book hub navbar from the shared Quarto navbar metadata."""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
NAVBAR_PATH = ROOT / "_global" / "navbar.yml"
OUTPUT_PATH = ROOT / "book" / "_includes" / "hub-navbar.html"


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "item"


def attrs_for_href(href: str, extra: dict[str, str] | None = None) -> str:
    attrs = {"href": href}
    if href.startswith("/"):
        attrs["data-arch2-href"] = href
    if extra:
        attrs.update({key: value for key, value in extra.items() if value})
    return " ".join(
        f'{html.escape(key)}="{html.escape(value, quote=True)}"'
        for key, value in attrs.items()
    )


def render_dropdown(item: dict, *, indent: str = "        ") -> list[str]:
    text = str(item["text"])
    menu_id = f"arch2-nav-menu-{slugify(text)}"
    lines = [
        f'{indent}<li class="nav-item dropdown">',
        (
            f'{indent}  <a class="nav-link dropdown-toggle" href="#" id="{menu_id}" '
            'data-bs-toggle="dropdown" aria-expanded="false">'
        ),
        f'{indent}    <span class="menu-text">{html.escape(text)}</span>',
        f"{indent}  </a>",
        f'{indent}  <ul class="dropdown-menu" aria-labelledby="{menu_id}">',
    ]
    for child in item.get("menu", []):
        child_text = str(child["text"])
        href = str(child["href"])
        lines.extend(
            [
                f"{indent}    <li>",
                (
                    f'{indent}      <a class="dropdown-item" {attrs_for_href(href)}>'
                    f'<span class="dropdown-text">{html.escape(child_text)}</span></a>'
                ),
                f"{indent}    </li>",
            ]
        )
    lines.extend([f"{indent}  </ul>", f"{indent}</li>"])
    return lines


def render_nav_item(item: dict, *, indent: str = "        ") -> list[str]:
    if item.get("menu"):
        return render_dropdown(item, indent=indent)
    text = str(item["text"])
    href = str(item["href"])
    return [
        f'{indent}<li class="nav-item">',
        (
            f'{indent}  <a class="nav-link" {attrs_for_href(href)}>'
            f'<span class="menu-text">{html.escape(text)}</span></a>'
        ),
        f"{indent}</li>",
    ]


def render_navbar(navbar: dict) -> str:
    title = html.escape(str(navbar["title"]))
    left_items = navbar.get("left", [])
    right_items = navbar.get("right", [])

    lines = [
        "<!-- Generated by .github/scripts/render_book_navbar.py; edit _global/navbar.yml. -->",
        '<nav class="navbar navbar-expand-lg arch2-hub-nav" aria-label="Architecture 2.0 hub">',
        '  <div class="navbar-container container-fluid">',
        '    <div class="navbar-brand-container mx-auto">',
        (
            '      <a class="navbar-brand" '
            f'{attrs_for_href("/index.html", {"aria-label": "Architecture 2.0 home"})}>'
        ),
        f'        <span class="navbar-title">{title}</span>',
        "      </a>",
        "    </div>",
        (
            '    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" '
            'data-bs-target="#arch2HubNavbarCollapse" aria-controls="arch2HubNavbarCollapse" '
            'aria-expanded="false" aria-label="Toggle navigation" '
            'onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">'
        ),
        '      <span class="navbar-toggler-icon"></span>',
        "    </button>",
        '    <div class="collapse navbar-collapse" id="arch2HubNavbarCollapse">',
        '      <ul class="navbar-nav navbar-nav-scroll me-auto">',
    ]
    for item in left_items:
        lines.extend(render_nav_item(item))
    lines.extend(
        [
            "      </ul>",
            '      <ul class="navbar-nav navbar-nav-scroll ms-auto">',
        ]
    )
    for item in right_items:
        lines.extend(render_nav_item(item))
    lines.extend(
        [
            "      </ul>",
            "    </div>",
            (
                '    <button type="button" class="btn quarto-search-button arch2-hub-search" '
                'aria-label="Search" onclick="window.quartoOpenSearch();">'
            ),
            '      <i class="bi bi-search" aria-hidden="true"></i>',
            "    </button>",
            "  </div>",
            "</nav>",
            "<script>",
            "(function () {",
            "  function placeHubNav() {",
            '    var nav = document.querySelector(".arch2-hub-nav");',
            "    if (!nav) {",
            "      return;",
            "    }",
            '    nav.querySelectorAll("[data-arch2-href]").forEach(function (link) {',
            '      link.setAttribute("href", link.getAttribute("data-arch2-href"));',
            "    });",
            "    if (nav.parentElement !== document.body || nav !== document.body.firstElementChild) {",
            "      document.body.insertBefore(nav, document.body.firstElementChild);",
            "    }",
            "  }",
            "",
            '  if (document.readyState === "loading") {',
            '    document.addEventListener("DOMContentLoaded", placeHubNav);',
            "  } else {",
            "    placeHubNav();",
            "  }",
            "})();",
            "</script>",
            "",
        ]
    )
    return "\n".join(lines)


def load_navbar() -> dict:
    with NAVBAR_PATH.open(encoding="utf-8") as handle:
        metadata = yaml.safe_load(handle) or {}
    navbar = metadata.get("website", {}).get("navbar")
    if not isinstance(navbar, dict):
        raise ValueError(f"{NAVBAR_PATH}: expected website.navbar mapping")
    return navbar


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the rendered navbar include is not up to date.",
    )
    args = parser.parse_args()

    rendered = render_navbar(load_navbar())
    if args.check:
        current = (
            OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        )
        if current != rendered:
            print(
                f"{OUTPUT_PATH} is out of date; run "
                ".github/scripts/render_book_navbar.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH} is up to date.")
        return 0

    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(
        f"Rendered {OUTPUT_PATH.relative_to(ROOT)} from {NAVBAR_PATH.relative_to(ROOT)}."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
