repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--unsafe]
-   repo: https://github.com/psf/black
    rev: 2a1c67e0b2f81df602ec1f6e7aeb030b9709dc7c  # 23.11.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: 960ead214cd1184149d366c6d27ca6c369ce46b6  # 1.16.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==23.11.0]
-   repo: local
    hooks:
    -   id: arch2-check
        name: arch2 precommit checks
        entry: ./arch2 check precommit
        language: system
        pass_filenames: false
        always_run: true
-   repo: local
    hooks:
    -   id: bibtex-tidy
        name: format bibtex
        entry: npx bibtex-tidy --modify --sort=key --align=14 --curly --blank-lines --sort-fields
        language: system
        files: \.bib$
        pass_filenames: true
