import re

with open(
    "book/chapters/05-architecture-environments-tool-interfaces/index.qmd", "r"
) as f:
    text = f.read()

# 1. Tool-Augmented LLMs (Origin Mismatch)
# Replace starting from "An autonomous AI, however, expects stateless, deterministic APIs. While recent advances..."
old_text1 = """An autonomous AI, however, expects stateless, deterministic APIs. While recent advances in "computer use" models allow AI to visually parse GUIs and literally move a mouse to click buttons, relying on visual GUI automation for architecture design is incredibly brittle and computationally inefficient. A pixel-based interaction model cannot guarantee the mathematical rigor and reproducibility required to tape out a multi-million dollar SoC. Because of this, system intent, a GUI, and permission to call a tool are vastly insufficient for robust architecture work."""
new_text1 = """Recent breakthroughs in the machine learning community, such as *Toolformer* [@SchickEtAl2023Toolformer], have proven that foundation models should not just emit raw text or unconstrained shell commands. To reliably interact with external software, models must be explicitly trained to invoke strict, typed APIs. This maps perfectly to the architectural domain. An autonomous AI expects stateless, deterministic APIs. While recent advances in "computer use" models allow AI to visually parse GUIs and literally move a mouse to click buttons, relying on visual GUI automation for architecture design is incredibly brittle and computationally inefficient. A pixel-based interaction model cannot guarantee the mathematical rigor and reproducibility required to tape out a multi-million dollar SoC. Because of this, system intent, a GUI, and permission to call a tool are vastly insufficient for robust architecture work."""
text = text.replace(old_text1, new_text1)

# 2. Reward Hacking (Semantic Gap)
# Replace starting from "The answer is a definitive *no*. We do not throw the traditional data overboard, because that data represents the unbreakable laws of physics..."
old_text2 = """The answer is a definitive *no*. We do not throw the traditional data overboard, because that data represents the unbreakable laws of physics, including timing closure, thermal limits, memory bandwidth, and physical routing congestion. Without this data, a generative AI is just a stochastic hallucination engine, while an optimization AI will ruthlessly exploit any flaws in an ungrounded reward function. The physical ground truth provided by traditional tools remains indispensable."""
new_text2 = """The answer is a definitive *no*. The machine learning community has long warned of **Reward Hacking** (or Goodhart's Law). As detailed in *Concrete Problems in AI Safety* [@AmodeiEtAl2016Concrete], if an AI is given a simple scalar reward, it will find loopholes to maximize that number while violating the actual intent. In architecture, if an environment merely reports Instructions Per Clock (IPC) as a reward, the Generator in the design loop will "hack" the World Model by hallucinating a physically impossible 10-Terabyte L1 cache. We do not throw the traditional data overboard, because that data represents the unbreakable laws of physics, including timing closure, thermal limits, memory bandwidth, and physical routing congestion. The physical ground truth provided by traditional tools remains indispensable to enforce these laws and prevent reward hacking."""
text = text.replace(old_text2, new_text2)

# 3. Offline RL (Killing Synchronous env.step)
# Replace starting from "In pedagogical AI tutorials, agents often interact with simulated games (like OpenAI Gym) using a synchronous `env.step()` function. The agent takes a discrete action..."
old_text3 = """In pedagogical AI tutorials, agents often interact with simulated games (like OpenAI Gym) using a synchronous `env.step()` function. The agent takes a discrete action, the simulation instantly steps forward in time, and the function returns the new state and a reward. However, because of the physical and economic constraints of real hardware design, this standard synchronous `env.step()` wrapper (which blocks execution until a scalar reward is returned) is fundamentally the wrong abstraction.\n\nBecause a blocking synchronous call will inevitably time out or hang when a placement job takes 40 hours or waits three days for an EDA license checkout, real tool chains require asynchronous, scarce, and protected execution mechanics."""
new_text3 = """In pedagogical AI tutorials, agents often interact with simulated games (like OpenAI Gym) using a synchronous `env.step()` function. This assumes an **Online Reinforcement Learning** paradigm, where the agent takes a discrete action, the simulation instantly steps forward in time, and the function returns the new state and a reward. However, as the ML community has increasingly recognized, online exploration is impossible in domains where simulation is dangerous or expensive [@LevineEtAl2020Offline]. Architecture is fundamentally an **Offline RL** or **Batch Optimization** problem. Because of the physical and economic constraints of real hardware design, this standard synchronous `env.step()` wrapper (which blocks execution until a scalar reward is returned) is fundamentally the wrong abstraction.\n\nBecause a blocking synchronous call will inevitably time out or hang when a placement job takes 40 hours or waits three days for an EDA license checkout, real tool chains require asynchronous, scarce, and protected execution mechanics."""
text = text.replace(old_text3, new_text3)

# 4. Sim-to-Real (Economic Reality of EDA)
# Inject right after "This economic clash dictates how environments must be constructed. As fidelity increases toward silicon, the sample budget shrinks exponentially from millions of cheap functional checks to handfuls of expensive layout runs."
old_text4 = """This economic clash dictates how environments must be constructed. As fidelity increases toward silicon, the sample budget shrinks exponentially from millions of cheap functional checks to handfuls of expensive layout runs.\n\nBecause of this reality, different tools return profoundly different things, and we cannot afford to blur them together."""
new_text4 = """This economic clash dictates how environments must be constructed. As fidelity increases toward silicon, the sample budget shrinks exponentially from millions of cheap functional checks to handfuls of expensive layout runs.\n\nTo navigate this harsh economic reality, we must look to the robotics community's solution for expensive environments: **Sim-to-Real Transfer**. Rather than training a robotic arm directly in the physical world (which is slow and risks destroying the hardware), researchers train the agent in a fast physics simulator and zero-shot transfer the learned policy to the real robot [@OpenAI2019Rubik]. Architecture requires a similar Sim-to-Real pipeline. The environment must expose cheap, cycle-approximate analytical models (the "Sim") for the first million exploratory proposals, and only trigger cycle-accurate RTL or full VLSI physical design (the "Real") to anchor the World Model when confidence drops.\n\nBecause of this reality, different tools return profoundly different things, and we cannot afford to blur them together."""
text = text.replace(old_text4, new_text4)

with open(
    "book/chapters/05-architecture-environments-tool-interfaces/index.qmd", "w"
) as f:
    f.write(text)

print("Done")
