#!/usr/bin/env python3
"""Render AWESOME.md from the canonical tool registry source entries."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
REGISTRY_DIR = ROOT / "tools" / "registry"
OUTPUT_PATH = ROOT / "AWESOME.md"

CATEGORY_ORDER = (
    "Simulation",
    "Proxy Models",
    "Agentic Workflows",
    "Data Representations",
    "Verification",
    "Benchmarks and Datasets",
    "Physical Design",
)

CATEGORY_HEADINGS = {
    "Simulation": "Simulation and Execution Environments",
    "Proxy Models": "Proxy Models and Surrogate Predictors",
    "Agentic Workflows": "Agentic Workflows and Generators",
    "Data Representations": "Data Representations and Hardware Vocabularies",
    "Verification": "Verification and Red-Teaming",
    "Benchmarks and Datasets": "Benchmarks and Datasets",
    "Physical Design": "Physical Design and EDA",
}

AVAILABILITY_LABELS = {
    "runnable": "Runnable",
    "source_available": "Source available",
    "benchmark_available": "Benchmark available",
    "dataset_available": "Dataset available",
    "paper_only": "Paper only",
    "unverified": "Unverified",
}


def _items() -> list[dict[str, Any]]:
    items = []
    for path in sorted(REGISTRY_DIR.glob("*.yml")):
        item = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        items.append(item)
    return sorted(
        items, key=lambda item: (item.get("order", 9999), item.get("title", ""))
    )


def _cell(value: Any) -> str:
    return str(value or "").replace("|", "\\|").replace("\n", " ").strip()


def render() -> str:
    items = _items()
    lines = [
        "# Awesome Architecture 2.0 [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)",
        "",
        "<!-- Generated by tools/render_awesome.py from tools/registry/*.yml. -->",
        "",
        "A curated list of tools, simulators, proxies, datasets, benchmarks, and",
        "workflows that support auditable AI-assisted computing-system design loops.",
        "The public registry at [arch2.mlsysbook.ai/tools](https://arch2.mlsysbook.ai/tools/)",
        "shows the same source records with availability and link-verification status.",
        "",
        "## How to Contribute",
        "",
        "Use the [tool submission form](https://github.com/harvard-edge/arch2/issues/new?template=submit_tool.yml)",
        "to propose an entry for maintainer review.",
        "",
        "## Contents",
        "",
    ]
    for category in CATEGORY_ORDER:
        heading = CATEGORY_HEADINGS[category]
        anchor = re.sub(r"[^a-z0-9]+", "-", heading.lower()).strip("-")
        lines.append(f"- [{heading}](#{anchor})")

    for category in CATEGORY_ORDER:
        category_items = [
            item for item in items if (item.get("categories") or [None])[0] == category
        ]
        lines.extend(
            [
                "",
                f"## {CATEGORY_HEADINGS[category]}",
                "",
                "| Tool or artifact | Availability | Description |",
                "| --- | --- | --- |",
            ]
        )
        for item in category_items:
            title = _cell(item.get("title"))
            url = _cell(item.get("url"))
            availability = AVAILABILITY_LABELS.get(
                item.get("artifact_availability"), "Unverified"
            )
            verified = _cell(item.get("last_verified"))
            status = (
                f"{availability}; link checked {verified}"
                if verified
                else f"{availability}; link not verified"
            )
            lines.append(
                f"| **[{title}]({url})** | {_cell(status)} | {_cell(item.get('description'))} |"
            )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Fail if AWESOME.md is stale."
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if actual != expected:
            print("AWESOME.md is stale; run tools/render_awesome.py")
            return 1
        print("AWESOME.md matches tools/registry/*.yml")
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"Rendered {OUTPUT_PATH.relative_to(ROOT)} from {len(_items())} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
